local AnimatedWaterPlane = require("Core.FileFormats.RSW.AnimatedWaterPlane")

describe("AnimatedWaterPlane", function()
	describe("GetTextureAnimationDuration", function()
		it("should return the texture cycling animation duration in milliseconds", function()
			assertEquals(AnimatedWaterPlane:GetTextureAnimationDuration(0), 0)
			assertEqualNumbers(AnimatedWaterPlane:GetTextureAnimationDuration(1), 533.333, 1E-3)
			assertEqualNumbers(AnimatedWaterPlane:GetTextureAnimationDuration(2), 1066.666, 1E-3)
			assertEqualNumbers(AnimatedWaterPlane:GetTextureAnimationDuration(3), 1600, 1E-3)
			assertEqualNumbers(AnimatedWaterPlane:GetTextureAnimationDuration(4), 2133.333, 1E-3)
			assertEqualNumbers(AnimatedWaterPlane:GetTextureAnimationDuration(5), 2666.666, 1E-3)
			assertEqualNumbers(AnimatedWaterPlane:GetTextureAnimationDuration(6), 3200, 1E-3)
			assertEqualNumbers(AnimatedWaterPlane:GetTextureAnimationDuration(7), 3733.333, 1E-3)
			assertEqualNumbers(AnimatedWaterPlane:GetTextureAnimationDuration(8), 4266.666, 1E-3)
		end)
	end)
end)
