local QuadTreeRange = require("Core.FileFormats.RSW.QuadTreeRange")

describe("QuadTreeRange", function()
	describe("GetBinaryStorageSizePerLevel", function()
		it("should return the required space (in bytes) for storing the given range on disk", function()
			assertEquals(QuadTreeRange:GetBinaryStorageSizePerLevel(0), 48)
			assertEquals(QuadTreeRange:GetBinaryStorageSizePerLevel(1), 192)
			assertEquals(QuadTreeRange:GetBinaryStorageSizePerLevel(2), 768)
			assertEquals(QuadTreeRange:GetBinaryStorageSizePerLevel(3), 3072)
			assertEquals(QuadTreeRange:GetBinaryStorageSizePerLevel(4), 12288)
			assertEquals(QuadTreeRange:GetBinaryStorageSizePerLevel(5), 49152)
		end)
	end)

	describe("GetBinaryStorageSize", function()
		it("should return the required space (in bytes) for storing the tree on disk", function()
			assertEquals(QuadTreeRange:GetBinaryStorageSize(), 65520)
			assertEquals(QuadTreeRange:GetBinaryStorageSize(0), 48)
			assertEquals(QuadTreeRange:GetBinaryStorageSize(1), 48 + 192)
			assertEquals(QuadTreeRange:GetBinaryStorageSize(2), 48 + 192 + 768)
			assertEquals(QuadTreeRange:GetBinaryStorageSize(3), 48 + 192 + 768 + 3072)
			assertEquals(QuadTreeRange:GetBinaryStorageSize(4), 48 + 192 + 768 + 3072 + 12288)
			assertEquals(QuadTreeRange:GetBinaryStorageSize(5), 48 + 192 + 768 + 3072 + 12288 + 49152)
		end)
	end)
end)
