local Buffer = require("Core.NativeClient.WebGPU.Buffer")

describe("Buffer", function()
	describe("GetAlignedSize", function()
		it("should return the padded size when a positive number value was passed", function()
			assertEquals(Buffer.GetAlignedSize(1), 4)
			assertEquals(Buffer.GetAlignedSize(2), 4)
			assertEquals(Buffer.GetAlignedSize(3), 4)
			assertEquals(Buffer.GetAlignedSize(4), 4)
			assertEquals(Buffer.GetAlignedSize(5), 8)
			assertEquals(Buffer.GetAlignedSize(6), 8)
			assertEquals(Buffer.GetAlignedSize(7), 8)
			assertEquals(Buffer.GetAlignedSize(8), 8)
		end)

		it("should return zero if a negative number was passed", function()
			assertEquals(Buffer.GetAlignedSize(0), 0)
		end)

		it("should return zero if zero was passed", function()
			assertEquals(Buffer.GetAlignedSize(0), 0)
		end)
	end)
end)
