name: Autoformat

on:
  pull_request:
    paths-ignore:
      - "README.MD"
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
    paths-ignore:
      - "README.MD"

jobs:
  check-format:
    name: Enforce consistent formatting
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install clang-format
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20
          which clang-format
          clang-format --version
          export CLANG_FORMAT=$(which clang-format)

      - name: Set up StyLua
        uses: JohnnyMorganz/stylua-action@v4.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check . --verbose
          version: v2.1.0

      - name: Run autoformat
        run: ./autoformat.sh

      - name: Check for inconsistent formatting
        run: git --no-pager diff --exit-code -b . # The -b is for inconsistent newlines, which we ignore (for now)
