name: Build and Release (Linux)

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths-ignore:
      - '**.md'
  create:
    # Any branch or tag
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event.pull_request.draft == false
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      # TODO: Re-enable once the WGPU issues have been resolved (tests still run on macOS/Win32)
      # - name: Install dependencies
      #   run: sudo apt update && sudo apt install libgtk-3-0 libwebkit2gtk-4.0-37 --yes

      # - name: Download Lua runtime
      #   run: ./download-runtime.sh && ./evo version

      # - name: Run automated tests
      #   run: ./test.sh

      # - name: Publish new release
      #   if: startsWith(github.ref, 'refs/tags/v')
      #   uses: softprops/action-gh-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
