name: Build and Release (Windows)

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths-ignore:
      - '**.md'
  create:
    # Any branch or tag
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event.pull_request.draft == false
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Download Lua runtime
        run: ./download-runtime.sh && ./evo.exe version
        shell: bash

      - name: Run automated tests
        run: ./test.sh
        shell: bash

      - name: Publish new release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: test.release
          body_path: CHANGELOG.MD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
