name: Static Analysis

on:
  pull_request:
    paths-ignore:
      - "README.MD"
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
    paths-ignore:
      - "README.MD"

jobs:
  check-format:
    name: Lint the codebase
    runs-on: ubuntu-latest
    env:
        RAGLITE_NAGA_VERSION: 26.0.0

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Scan for missing executable flags # They can get lost while rebasing on Windows
        run: |
          git ls-files --stage | grep '\.sh' || true
          git ls-files --stage | grep '\.sh' | grep '100644' || true
          git ls-files --stage | grep '\.sh' | grep -v '100644'

      - name: Download luacheck
        run: curl --silent --location --output luacheck https://github.com/lunarmodules/luacheck/releases/download/v1.1.0/luacheck

      - name: Run luacheck
        run: chmod +x luacheck && ./luacheck .

      - name: Cache naga binary
        id: cache-naga
        uses: actions/cache@v4
        with:
          path: naga
          key: naga-v${{ env.RAGLITE_NAGA_VERSION }}
          restore-keys: |
            naga-v${{ env.RAGLITE_NAGA_VERSION }}

      - name: Install naga-cli
        if: steps.cache-naga.outputs.cache-hit != 'true'
        run: |
          cargo install naga-cli@${{ env.RAGLITE_NAGA_VERSION }}
          cp -v $(which naga) .
          echo $(pwd) >> $GITHUB_PATH
          naga --version

      - name: Validate WGSL shaders
        run: ./validate-shaders.sh
