name: Compile TypeScript sources

on:
  pull_request:
    branches:
      - main

jobs:
  test-deploy:
    name: Create JavaScript app bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: Core/WebClient/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: Core/WebClient

      - name: Run checks
        run: npm run checks
        working-directory: Core/WebClient

      - name: Run unit tests
        run: npm test
        working-directory: Core/WebClient

      - name: Run esbuild
        run: npm run build
        working-directory: Core/WebClient
